version: '3'
services:
  postgres:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: 'coindb'
      POSTGRES_USER: 'admin'
      POSTGRES_PASSWORD: 'admin'
    restart: always


